#!/usr/bin/env python
import os
from xml.dom.minidom import *

path = "logo/assets/celebrities/logos"

for dir_entry in os.listdir(path):
 print dir_entry
 dir_entry_new = str(dir_entry)
 dir_entry_new = dir_entry_new.replace("jpg","png")
 print dir_entry_new
 os.rename(path+'/'+dir_entry,path+'/'+dir_entry_new)
