#!/usr/bin/env python
import os
from xml.dom.minidom import *
import unicodedata
import codecs
import random

# Python Script to generate content for ImageData.as File
# Change the path's appropriately to the folder where respective assets are placed
# Output is written to a file OutData.txt
# Input is given through a file inp.txt

lis = ['A','E','O','S','I','E','U','M','L','A','E','P','R','N']
def scrub (s):
	while(len(s)<14):
		a = random.randint(0, 13)
		s += lis[a]
	ss = ''.join(random.sample(s,len(s)))
	#print s + "--->" + ss
	return ss 


xmlPath    = 'logo/assets/flags/level-data/LevelPack'
imgPath    = 'logo/assets/flags/logos/'
printPath  = '../../../../../assets/flags/logos/'
out        = open('OutData.txt', 'w')
inp				 = open('inp.txt','r')
it1 = 1
arr = []
for line in inp:
    arr.append( line.replace('\n','') )
inp.close()

while (it1!=21):
	newPath = xmlPath+str(arr[it1-1])+".xml"
	if (os.path.exists(newPath)):
		file = codecs.open(newPath, "r", "utf-8")
		data = file.read()
		file.close()
	else :
		break
	print newPath
	data = unicodedata.normalize('NFKD', data).encode('ascii','ignore')
	datacopy = data
	origdata = data
	data = data.replace('&','and')
	dom = parseString(data)
	xmlTag = dom.getElementsByTagName('options')
	ansTag = dom.getElementsByTagName('answer')
	it2 = 0
	while it2 < len(xmlTag):
		xmlData = xmlTag[it2].toxml().replace('<options>','').replace('</options>','');
		ansData = ansTag[it2].toxml().replace('<answer>','').replace('</answer>','');
		xmlDataNew = ansData.replace(' ','').upper();
		while(xmlDataNew.find(" ")!=-1):
			xmlDataNew = xmlDataNew.replace(" ","");
		ansDataNew = ansData.upper();
		if len(str(xmlDataNew))>14 :
			print "LONG : "+ansData
		xmlDataNew = scrub(xmlDataNew);
		datacopy = datacopy.replace(xmlData,xmlDataNew);
		datacopy = datacopy.replace(ansData,ansDataNew);
		it2 += 1
	it1 += 1
	if origdata!=datacopy :
		fileout = open(newPath,'w')
		fileout.write(datacopy)